wip

diff --git a/musl-cross-make-confs/Makefile.arch_indep b/musl-cross-make-confs/Makefile.arch_indep
--- a/musl-cross-make-confs/Makefile.arch_indep
+++ b/musl-cross-make-confs/Makefile.arch_indep
@@ -140,14 +140,16 @@ ARCH         := $(shell uname -m | sed 's/^\(arm\).*/\1/g')
 GCCVER       := 9.4.0
 BINUTILSVER  := 2.33.1
 # XXX - gettexttiny breaks between 1.2.4 and 1.2.5; need to bisect to figure out where
-#MUSLVER      := 1.2.5
-MUSLVER      := 1.2.4
+MUSLVER      := 1.2.5
+#MUSLVER      := 1.2.4
 ISLVER       := 0.21
 #LINUXVER     := 4.4.10
 
 ## musl
 #MUSLSHA1 := null
 #MUSLFILE := musl-$(MUSLVER).tar.gz
+MUSL_MISC_REPO := https://github.com/ryanwoodsmall/musl-misc
+MUSL_MISC_RAW  := https://raw.githubusercontent.com/ryanwoodsmall/musl-misc/refs/heads/master
 
 # form our triplet, arm needs to be hardware float
 TRIPLET_BASE := $(ARCH)-linux-musl
@@ -231,9 +233,9 @@ prereqs:
 	echo 'if this fails, make sure you can write to $(CWSTATICINST) or its parent directory'
 	mkdir -p $(CWSTATICINST)
 	echo
-	#echo 'if this fails, make sure you are running in a musl-cross-make git checkout'
-	#test -e $(CONFMAKDIST)
-	#echo
+	echo 'if this fails, make sure you are running in a musl-cross-make git checkout'
+	test -e $(CONFMAKDIST)
+	echo
 
 # $(CONFMAK) common toolchain options
 $(CONFMAK).common: cleanconfs
@@ -288,16 +290,25 @@ $(CONFMAK).static: $(CONFMAK).common
 
 # custom ld.so path stuff
 get_patches: remove_patches
+	# XXX - hackity hacky hack
 	# XXX - change when default versions are updated
 	# XXX - wget needs to be changed to whatever $(DL_CMD) is set to
-	mkdir -p ./patches/gcc-$(GCCVER) || true
-	cd ./patches/gcc-$(GCCVER)/ ; curl -kLO https://raw.githubusercontent.com/ryanwoodsmall/musl-misc/master/musl-cross-make-confs/patches/9999-crosware-ldso_gcc-$(GCCVER).diff
-	cd ./patches/gcc-$(GCCVER)/ ; curl -kLO https://raw.githubusercontent.com/ryanwoodsmall/musl-misc/master/musl-cross-make-confs/patches/9999-crosware-gcc-$(GCCVER)-libstdcpp-v3-configure.diff
-	mkdir -p ./patches/binutils-$(BINUTILSVER) || true
-	cd ./patches/binutils-$(BINUTILSVER)/ ; curl -kLO https://raw.githubusercontent.com/ryanwoodsmall/musl-misc/master/musl-cross-make-confs/patches/9999-crosware-ldso_binutils-$(BINUTILSVER).diff
+	#
+	# XXX - musl???
+	mkdir -p ./patches/musl-$(MUSLVER) || true
+	#cd ./patches/musl-$(MUSLVER)/ ; curl -kLO $(MUSL_MISC_RAW)/patches/0001-iconv-fix-erroneous-input-validation-in-EUC-KR-decod.patch
+	#cd ./patches/musl-$(MUSLVER)/ ; curl -kLO $(MUSL_MISC_RAW)/patches/0002-iconv-harden-UTF-8-output-code-path-against-input-de.patch
+	# XXX - old musl
 	#mkdir -p ./patches/musl-$(MUSLVER) || true
-	#cd ./patches/musl-$(MUSLVER) ; curl -kLo 9999-crosware-CVE-2020-28928.diff https://raw.githubusercontent.com/ryanwoodsmall/musl-misc/master/patches/CVE-2020-28928.patch
-	# XXX - hackity hacky hack
+	#cd ./patches/musl-$(MUSLVER) ; curl -kLo 9999-crosware-CVE-2020-28928.diff $(MUSL_MISC_RAW)/patches/CVE-2020-28928.patch
+	#
+	# gcc
+	mkdir -p ./patches/gcc-$(GCCVER) || true
+	cd ./patches/gcc-$(GCCVER)/ ; curl -kLO $(MUSL_MISC_RAW)/musl-cross-make-confs/patches/9999-crosware-gcc-$(GCCVER)-libstdcpp-v3-configure.diff
+	#
+	# binutils
+	mkdir -p ./patches/binutils-$(BINUTILSVER) || true
+	cd ./patches/binutils-$(BINUTILSVER)/ ; curl -kLO $(MUSL_MISC_RAW)/musl-cross-make-confs/patches/9999-crosware-ldso_binutils-$(BINUTILSVER).diff
 
 remove_patches:
 	rm -f ./patches/*/*crosware* || true
